import java.util.Scanner;



//Todo:
// Search the internet for an EAN database in CSV format (or have one generated by ChatGPT). Use this CSV file as input.
// Store the quantity of each product in stock. When a product is ordered, decrease the inventory. If a product is out of stock, it cannot be ordered.
// Enable additional workflows for goods in and out. When goods are received, increase the inventory. When goods are dispatched (e.g., due to water damage or theft), decrease the inventory.
// Keep a log of all inventory changes, with links to the orders (or goods in and out) that caused these changes.


public class Main {
    public static void main(String[] args) {

        //Setup
        ProductRepo products = new ProductRepo();
        Scanner scanner = new Scanner(System.in);

        //Wenn zu faul von hand anzulegen
        products.addProduct(new Product(15.50,"Stifte in allen Farben","prd001"));
        products.addProduct(new Product(2.50,"Ordner","prd002"));
        products.addProduct(new Product(20.00,"150 Kugelschreiber","prd003"));
        products.addProduct(new Product(1.50,"Collegeblock","prd004"));
        products.addProduct(new Product(15.50,"Wasserfarbe","prd005"));

        System.out.println("\u001B[1m Product management system\u001B[0m");
        System.out.println("\u001B[1m \u001B[32m 1.\u001B[0m Neues Produkt anlegen");
        System.out.println("\u001B[1m \u001B[32m 2.\u001B[0m Neue Bestellung anlegen");
        System.out.println("\u001B[1m \u001B[32m 3.\u001B[0m Alle Produkte anzeigen\n");
        System.out.println("\u001B[1mWählen Sie ihre option: \u001B[0m");
        int input = scanner.nextInt();

        switch(input){
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
            default:
                break;
        }

    }
}
